name: "Diematic Solar"
version: "1.0.2"
slug: "diematic_solar"
description: "Publie les données d'une chaudière Diematic sur MQTT et Home Assistant"
url: "https://github.com/ploufe/Diematic_solar"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_topic_prefix: "home/heater"
  mqtt_client_id: "boiler"
  modbus_host: "192.168.1.X"
  modbus_port: 20108
  regulator_address: "0x0A"
  interface_address: "0x32"
  regulator_type: "Diematic3"
  timezone: "CET"
  time_sync: false
  period: 10
  enable_circuit_a: false
  enable_circuit_b: false
  discovery_enable: true
  discovery_prefix: "homeassistant"
  serial_device: ""
  solar_enabled: true
schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mqtt_topic_prefix: str
  mqtt_client_id: str
  modbus_host: str
  modbus_port: port
  regulator_address: str
  interface_address: str
  regulator_type: list(Diematic3|Diematic4|DiematicDelta)
  timezone: str
  time_sync: bool
  period: int
  enable_circuit_a: bool
  enable_circuit_b: bool
  discovery_enable: bool
  discovery_prefix: str
  serial_device: str
  solar_enabled: bool
