[loggers]
keys=root

[logger_root]
level=INFO
handlers=console

[formatters]
keys=timedRotatingFormatter

[formatter_timedRotatingFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=

[handlers]
keys=console

[handler_console]
class=StreamHandler
formatter=timedRotatingFormatter
args=(sys.stdout,)
